version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080       # qBittorrent Web UI
      - 1111:8989       # Sonarr
      - 2222:7878       # Radarr
      - 3333:9696       # Prowlarr
    volumes:
      - ${CONFIG_ROOT}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - TZ=Asia/Kolkata
      - UPDATER_PERIOD=24h
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DOWNLOAD_FOLDER}:/downloads
      - ${MEDIA_FOLDER}:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DOWNLOAD_FOLDER}:/downloads
      - ${MEDIA_FOLDER}:/media
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
      - ${DOWNLOAD_FOLDER}:/downloads
      - ${MEDIA_FOLDER}:/media
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${DOWNLOAD_FOLDER}:/downloads
      - ${MEDIA_FOLDER}:/media
    ports:
      - 4444:6767
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DOWNLOAD_FOLDER}:/downloads
    restart: unless-stopped

networks: {}
