services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8888:80
    volumes:
      - /:/srv
      - ${CONFIG_ROOT}/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
